/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemontRouteImport } from './routes/remont'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PeretyazhkaRouteImport } from './routes/peretyazhka'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as KejsyRouteImport } from './routes/kejsy'
import { Route as CenyRouteImport } from './routes/ceny'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const RemontRoute = RemontRouteImport.update({
  id: '/remont',
  path: '/remont',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PeretyazhkaRoute = PeretyazhkaRouteImport.update({
  id: '/peretyazhka',
  path: '/peretyazhka',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const KejsyRoute = KejsyRouteImport.update({
  id: '/kejsy',
  path: '/kejsy',
  getParentRoute: () => rootRouteImport,
} as any)
const CenyRoute = CenyRouteImport.update({
  id: '/ceny',
  path: '/ceny',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/ceny': typeof CenyRoute
  '/kejsy': typeof KejsyRoute
  '/kontakty': typeof KontaktyRoute
  '/peretyazhka': typeof PeretyazhkaRoute
  '/privacy': typeof PrivacyRoute
  '/remont': typeof RemontRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/ceny': typeof CenyRoute
  '/kejsy': typeof KejsyRoute
  '/kontakty': typeof KontaktyRoute
  '/peretyazhka': typeof PeretyazhkaRoute
  '/privacy': typeof PrivacyRoute
  '/remont': typeof RemontRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/ceny': typeof CenyRoute
  '/kejsy': typeof KejsyRoute
  '/kontakty': typeof KontaktyRoute
  '/peretyazhka': typeof PeretyazhkaRoute
  '/privacy': typeof PrivacyRoute
  '/remont': typeof RemontRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/ceny'
    | '/kejsy'
    | '/kontakty'
    | '/peretyazhka'
    | '/privacy'
    | '/remont'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/ceny'
    | '/kejsy'
    | '/kontakty'
    | '/peretyazhka'
    | '/privacy'
    | '/remont'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/ceny'
    | '/kejsy'
    | '/kontakty'
    | '/peretyazhka'
    | '/privacy'
    | '/remont'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CenyRoute: typeof CenyRoute
  KejsyRoute: typeof KejsyRoute
  KontaktyRoute: typeof KontaktyRoute
  PeretyazhkaRoute: typeof PeretyazhkaRoute
  PrivacyRoute: typeof PrivacyRoute
  RemontRoute: typeof RemontRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/remont': {
      id: '/remont'
      path: '/remont'
      fullPath: '/remont'
      preLoaderRoute: typeof RemontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peretyazhka': {
      id: '/peretyazhka'
      path: '/peretyazhka'
      fullPath: '/peretyazhka'
      preLoaderRoute: typeof PeretyazhkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kejsy': {
      id: '/kejsy'
      path: '/kejsy'
      fullPath: '/kejsy'
      preLoaderRoute: typeof KejsyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceny': {
      id: '/ceny'
      path: '/ceny'
      fullPath: '/ceny'
      preLoaderRoute: typeof CenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CenyRoute: CenyRoute,
  KejsyRoute: KejsyRoute,
  KontaktyRoute: KontaktyRoute,
  PeretyazhkaRoute: PeretyazhkaRoute,
  PrivacyRoute: PrivacyRoute,
  RemontRoute: RemontRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
